# ------- anticheat -------
# none: show no plugins to cheater
# punish: run a console command on cheater
# fakelist: returns a fake list of plugins to the cheater
punish-method: punish
# fake list of plugins to show if the method is 'fakelist'
fakelist:
- fakeplugin1
- fakeplugin2
# command to run if the method is 'command', use <player> for cheater's name
command: kick <player> cheating.
# message to send to player if they run a command they can't see or it doesn't exist.
message: "&cUnknown Command!"

# ------- tab completions -------
# defines what commands each group can see, uses the group.x permission (ex. group.admin)
# OP players will see every command no matter what
# must rejoin to see the effects
group:
  admin:
    - $default # this means all commands from 'default' will be included in 'admin'
    - ban
    - kick
    - help
  default:
    - spawn